### ISSUE TITLE
预览时，移除一项数据

### ISSUE THREAD

**Issue by JiayuanChan** [iielse/imageviewer#100]
当预览时，某些情况下，需要删除其中的一条数据，请问该如何做？？？

**Comment by iielse** [comment]
这个目前没支持. 要支持框架要改变很多东西. 因为我用的paging来实现的数据加载,paging对增删改似乎.. 集成者的代码也会开始变得麻烦. 
但是这个是可以支持的. 我近期会开始尝试增加这个功能.

**Comment by iielse** [comment]
@JiayuanChan 确认一下，在编辑删除的时候，你有需要预览大图的所有的数据源吗？还是说数据需要异步来源于网络

**Comment by iielse** [comment]
@JiayuanChan 移除功能有了，移除后选中谁呢.第一项?上一项

**Comment by iielse** [comment]
实现代码在 https://github.com/iielse/imageviewer/tree/viewer_remove_item 上。可运行功能已实现。

我经过长考，移除和修改功能暂时不打算合入主分支。这个库目前更集中于数据的展示

**Comment by JiayuanChan** [comment]
@ielse 不好意思，才来看到，删除后，如果有后面一项数据，就显示后一项，没有就先上前一项，如果没得数据了，就结束预览。

**Comment by JiayuanChan** [comment]
> @JiayuanChan 确认一下，在编辑删除的时候，你有需要预览大图的所有的数据源吗？还是说数据需要异步来源于网络

我是在预览的时候长按可以有选项删除，这些数据源是已经获取到的(提前从网络获取了)

**Comment by iielse** [comment]
诸多考虑后 本库目前不实现删除修改功能. 仅集中于数据的展示.

但该功能的实现思路代码已提供.
viewer_remove_item 分支上有基于paging的修改数据更新列表的方案
https://github.com/iielse/imageviewer/blob/viewer_remove_item/imageviewer/src/main/java/com/github/iielse/imageviewer/adapter/Repository.kt

详见方法`removeAll `.
