### ISSUE TITLE
视频不可拖拽

### ISSUE THREAD

**Issue by tokiii** [iielse/imageviewer#102]
展示视频的时候不可拖拽

**Comment by iielse** [comment]
我感觉 视频方面 可能需要再大改一波 拓展一个 ItemType.VIDEO. 这个可能比较久. 我要考虑一些细节

**Comment by iielse** [comment]
@tokiii 再过一段时间就写出来了 应该

**Comment by iielse** [comment]
主要逻辑已经写了90%. 在 video 分支上面. 还有点小东西，要收尾了.

**Comment by iielse** [comment]
@tokiii  video 最新代码已经怼上去了，帮忙看下有没有啥问题，或者要补充的需求点，过段时间问题不大就把video发布了。

**Comment by tokiii** [comment]
@iielse 我今天运行了下代码，基本上没啥问题，就是在视频播放的时候可不可以点击出现播放控制栏，类似微信

**Comment by iielse** [comment]
微信朋友圈的也是自动循环播放没有进度条呀。

**Comment by tokiii** [comment]
我是在聊天记录里面看到的，我做的也是聊天记录页(⊙︿⊙)

**Comment by iielse** [comment]
从通用框架考虑 这些需要开发者实现，我这边把SimpleExoPlayer暴露出来就可以了，因为ui排版是不需要我掌控的。 然后config里面提供是否要 autoPlay 的配置 你觉得呢

**Comment by iielse** [comment]
我可以尝试写在demo中. 后面会有

**Comment by tokiii** [comment]
嗯嗯，可以了大佬，我就是提个建议，已经很完美了，O(∩_∩)O哈哈~

**Comment by iielse** [comment]
近期会把视频发上去的,我自己再多测测
