### ISSUE TITLE
请教一个关于状态栏的问题

### ISSUE THREAD

**Issue by 1wayticket** [iielse/imageviewer#103]
版本 2.0.11
您好,我们的图片放大依赖的activity页面布局都是延伸到状态栏的,而预览Fragment依赖的是DailogFragment.弹出DialogFragment预览时会出现计算位置偏移,也就共享动画初始位置 Y轴方向会比实际位置多一个状态栏高度,请问有没有什么方法可以规避一下,谢谢.

**Comment by iielse** [comment]
你是说 TRANSITION_OFFSET_Y 吗. 你可以把偏移值设置一下， demo 里面有

**Comment by wyy-dev** [comment]
Config.INSTANCE.setTRANSITION_OFFSET_Y(BarUtils.getStatusBarHeight());
这个我也设置了，但是没有生效
