### ISSUE TITLE
手势滑动效果体验太差

### ISSUE THREAD

**Issue by victorfan336** [iielse/imageviewer#104]
手势滑动效果体验太差，尤其是第一次放大图片的时候，经常容易无法放大，或者放大一点后卡住无法放大了，又或者是响应了左滑或者右滑，我用的是PhotoView的加载方式，感觉跟PhotoView的放大效果差好多，这个可以改进吗？
谢谢了。

**Comment by iielse** [comment]
你是希望在多指触摸屏幕的时候不要触发相应翻页滑动的意思吗.

**Comment by victorfan336** [comment]
> 你是希望在多指触摸屏幕的时候不要触发响应翻页滑动的意思吗.
感谢回复，可能是我没描述清楚。
我其实是想放大图片，但是给人感觉放大图片很吃力。经常在图片放大一点后就会出发翻页，导致放大图片动作终止，或者直接就是翻页没有放大图片，但其实我是两个手指在上面进行图片放大的。
你对比PhotoView的demo看就知道效果差距了。
希望可以改进下，加油！

**Comment by victorfan336** [comment]
开始以为可能是可以翻页导致的放大不流畅，没想到只有一张图片时，放大也不流畅。
单图：
1.放大手势很难检测到，经常两个手指放大滑动没反应，很常见
2.图片放大到一点点后就卡住并终止了手势继续放大，需要松手后再次触发才有效。这个同上面说的情况。

**Comment by iielse** [comment]
好的，我把viewpager2的滑动事件和photoView缩放的事件拆开了，后面可以再试试

**Comment by iielse** [comment]
@victorfan336 我刚才修改了触摸相关代码后，用demo自测了10多次，双击打开大图后，直接2个手指在上面进行图片放大，没有被翻页影响了，麻烦再试试，谢谢

**Comment by victorfan336** [comment]
@iielse 嗯 已经测过了，可以了，辛苦了。为你的及时响应点赞👍。
