### ISSUE TITLE
demo  indicator  出错问题

### ISSUE THREAD

**Issue by IurKwan** [iielse/imageviewer#108]
LoadAllAtOnce情况下发现由于ImageViewerAdapter未执行onBindViewHolder,导致setCurrentItem onPageSelected  无法找到该RecyclerView.ViewHolder直接return  导致自定义方法onPageSelected没有执行

**Comment by iielse** [comment]
ok bug 以复现.我研究下

**Comment by iielse** [comment]
修好了
