### ISSUE TITLE
提供自定义视频播放器功能

### ISSUE THREAD

**Issue by zhangkun0018** [iielse/imageviewer#111]
不使用分页加载，使用一次性加载数据，会出现个问题。当前显示的Item的holder为null，就是下面这个地方
![1597397741](https://user-images.githubusercontent.com/23331766/90235954-b09e3980-de54-11ea-810d-ea43ec223f78.png)

**Comment by iielse** [comment]
这个今天下午刚解决过. 麻烦拉下代码在帮忙试试， 非常感谢！

**Comment by iielse** [comment]
你点下 [video simple] 就是集成 controlView 的. ui需要开发者自定义

**Comment by iielse** [comment]
![CA28D37B9458D9CBEC11C68FEE701764](https://user-images.githubusercontent.com/7521943/90241657-1642f380-de5e-11ea-90ab-0647a24fa501.jpg)
