### ISSUE TITLE
嵌套动画问题

### ISSUE THREAD

**Issue by wang88911314** [iielse/imageviewer#112]
RecyclerView 嵌套RecyclerView实现动态效果后点击图片查看 动画返回位置不对怎么弄呢？

**Comment by iielse** [comment]
Transformer 实现的不对

**Comment by iielse** [comment]
https://github.com/iielse/imageviewer/issues/106

**Comment by wang88911314** [comment]
TransitionViewsRef.INSTANCE.provideTransitionViewsRef(TransitionViewsRef.KEY_MAIN).put(data.id(),holder.getView(R.id.imageView));  单recyclerView 没有问题，但recyclerViewA嵌套recyclerViewB 后recyclerViewB 中图片实现跳转位置就有问题。能不能给个demo,kotlin 不是怎么能懂，万分感激

**Comment by iielse** [comment]
后面会在demo上补充 recyclerView 嵌套 recyclerView 的场景的

**Comment by wang88911314** [comment]
非常感谢，问题已解决。使用了重复的photoId 导致的。测试用了同一个dataList。还有一个问题请教一下，一般这种格式显示时都是以9宫格显示，超出会显示多余数量，浏览大图时候浏览大于第9张时如何动画返回到第9张上呢？

**Comment by iielse** [comment]
Transformer 的原理 我给你photoId 你给我原图位置. 有原图位置过渡动画回到原图，没有就是放大淡出. 具体逻辑见 TransitionEndHelper。  最近比较忙. recyclerView 嵌套的 代码就不补充了.  
所以对于你这个问题返回到第9张，你就在 Transformer实现上给第9张图的位置信息就好。这些都是开发者的自定义业务
