### ISSUE TITLE
图片预览时可以添加个图片的加载进度吗

### ISSUE THREAD

**Issue by zhangkun0018** [iielse/imageviewer#115]
如题，在网络部好的情况下，预览时一直显示黑色的背景，只有图片加载完了才能显示出来。可以添加个图片加载的进度吗？

**Comment by iielse** [comment]
实现`ImageLoader`接口的`load`方法， 你需要在里面追加自定义实现.
demo里面`load (view: SubsamplingScaleImageView)` 的代码块中有相关逻辑. 可搜索参照`findLoadingView`相关代码. 你可以将这些逻辑套用到 `load (view: ImageView)` 重载方法里

**Comment by iielse** [comment]
若有问题再重新打开
