### ISSUE TITLE
状态栏显示异常 三星A51 安卓10

### ISSUE THREAD

**Issue by SmileEveryDayDay** [iielse/imageviewer#116]
[device-2020-10-16-113927.zip](https://github.com/iielse/imageviewer/files/5389064/device-2020-10-16-113927.zip)
三星a51 安卓10 版本 显示有一条间隙 demo代码

**Comment by iielse** [comment]
个人推测 demo 取 statusBarHeight 的方法不标准，应该从 `WindowInsets` 中取 `systemWindowInsetTop`.

**Comment by SmileEveryDayDay** [comment]
和状态栏没有关系 我试着把全屏的TRANSITION_OFFSET_Y都修改成0 还是一样 但是只要使用 FullScreenImageViewerDialogFragment这个就不会有这样的bug  但是这个自定义DialogFragment 必须每次onDestroyView 恢复打开大图查看前的状态栏

**Comment by iielse** [comment]
分析了很久 惭愧暂时没想到原因  :( .  感觉像系统bug

**Comment by SmileEveryDayDay** [comment]
不知道为什么dialog的宽度设置成屏幕的宽度就不会有这个bug 我也搞不懂为啥 难不成三星把这弄了比例
![QQ截图20201016160805](https://user-images.githubusercontent.com/19358621/96230329-019fea80-0fca-11eb-84c7-b1997d6d17f4.png)
