### ISSUE TITLE
增加PDF的预览效果支持

### ISSUE THREAD

**Issue by HelloPeng** [iielse/imageviewer#117]
看目前的代码，模仿加入视频预览的效果，通过判断对应的ItemType加入对应的ViewHolder放入PDF预览的View，不知道现在有没有其他的方案提供。如果是加入新的预览效果需要修改代码代码话，感觉这样修改入侵性太大，而且里面的手势处理交互逻辑也不是很清楚，不知道加入后会不会有很多其他的问题。是不是考虑通过提供接口，方便我们自己扩展需要展示效果的View，具体手势的处理不需要我们关心。

**Comment by iielse** [comment]
当时考虑到常见的类型最多有常规图/超大图.后面又增加了Video.认为已经是极限了.现在又知道原来有pdf,我怀疑还有更多.确实需要提供自定义的类型拓展.但是考虑到各种因素,这个成品代码应该要改很久.
你可以暂时尝试 convert pdf to png 的路子.

**Comment by HelloPeng** [comment]
> 当时考虑到常见的类型最多有常规图/超大图.后面又增加了Video.认为已经是极限了.现在又知道原来有pdf,我怀疑还有更多.确实需要提供自定义的类型拓展.但是考虑到各种因素(996小声哔哔),这个成品代码应该要改很久.
> 你可以暂时尝试 convert pdf to png 的路子.

我按照视频显示的思路，今天已经解决了我的需求了（领导看了很满意）。本来想自己动手封装一下来，奈何自己水平有限，只能是先以解决问题为目标了。希望这个扩展能早日实现，也让我参考参考😋

**Comment by iielse** [comment]
可以可以，有时间能不能把你的pdf出一个demo代码放在github上给我参考参考 /抱拳 。等我项目不忙了应该会有时间来继续更新优化这个库

**Comment by HelloPeng** [comment]
> 可以可以，有时间能不能把你的pdf出一个demo代码放在github上给我参考参考 /抱拳 。等我项目不忙了应该会有时间来继续更新优化这个库

大佬代码已经传到github上了，地址是：[传送门](https://github.com/HelloPeng/ImageViewer)
