### ISSUE TITLE
IllegalStateException: Pages must fill the whole ViewPager2 (use match_parent)

### ISSUE THREAD

**Issue by wishdusk** [iielse/imageviewer#118]
按照示例写，跑起来抛这个异常

**Comment by iielse** [comment]
提供的信息太少。在`ImageViewerAdapter`中增加了新的自定义类型，并且对应的xml的根View不是match_parent或者期间动态修改过宽高 就会报这个错哦。如果是这个情况，你可以套一个FrameLayout

**Comment by iielse** [comment]
提供内容过少. 没有具体信息. 没法分析

**Comment by liamyu** [comment]
刚刚也遇到这个问题，是因为覆写Photo接口的时候itemType()随便返回了个0，返回ItemType.PHOTO就好了😂
