### ISSUE TITLE
怎么实现类似startActivityForResult的功能呢？

### ISSUE THREAD

**Issue by zhf99love** [iielse/imageviewer#119]
比如我打开了收藏的相册，我点开图片，长按删除图片，我想让列表页获取监听，除了EventBus，还有更优雅的解法么？

**Comment by iielse** [comment]
比EventBus更优雅的解法..优雅. 这个不太清楚
总之传递事件终归需要注册监听的.

**Comment by iielse** [comment]
这个问题似乎和这个库关系不大.

**Comment by iielse** [comment]
我做的话.UI列表的事件.我比较喜欢在adapter这里定义接口.然后在fragment/activity 这里设置解除监听的.就和这个库的ImageViewerAdapterListener一样的. 列表会用paging+livedata实现的.看数据跨不跨页面.repository简单点可以做成单利.只是想删数据的话以上就可以了. 如果还要得到删除这个'动作'. 我会再做一个livedata.在数据变化的时候维护它. 类似ImageViewerActionViewModel.actionEvent 这样的形式来做'事件传递'. 这种方式sticky不很简单.也不是不能做.就是还想到其他页面感知这个删除事件. 看需求.代码根据需求来变化的. 以上只是我个人的代码习惯而已. 什么更优雅每个人看法都不一样的.

**Comment by zhf99love** [comment]
感谢
