### ISSUE TITLE
用 subsamplingView 展示长图的时候，上下滑动和拖拽冲突了

### ISSUE THREAD

**Issue by bytebubbles** [iielse/imageviewer#120]

**Comment by iielse** [comment]
是subsamplingView在放大的情况下不能下拉关闭的意思吗. 
请在说具体点. 麻烦顺便提供长图的数据源. 和复现的步骤.以及你期望的结果

**Comment by bytebubbles** [comment]
> 是subsamplingView在放大的情况下不能下拉关闭的意思吗.
> 请在说具体点. 麻烦顺便提供长图的数据源. 和复现的步骤.以及你期望的结果

不好意思，就是使用 subsamplingView 展示长图时，向下滑动查看图片，滑动一小段距离后就触发拖拽事件了

https://user-images.githubusercontent.com/33546683/115006890-f6c40500-9edb-11eb-9fcb-12acc9681657.mp4

**Comment by iielse** [comment]
是不是设置过SUBSAMPLING_SCALE_TYPE.  看起来 SubsamplingScaleImageView2.handleDispatchTouchEvent 的内部逻辑还有问题.
你可以尝试先用 SubsamplingScaleImageView.SCALE_TYPE_CENTER_INSIDE 试试
或者当当前页面为SubsamplingScaleImageView的时候关闭Config.SWIPE_DISMISS

**Comment by bytebubbles** [comment]
> 是不是设置过SUBSAMPLING_SCALE_TYPE. 看起来 SubsamplingScaleImageView2.handleDispatchTouchEvent 的内部逻辑还有问题.
> 你可以尝试先用 SubsamplingScaleImageView.SCALE_TYPE_CENTER_INSIDE 试试
> 或者当当前页面为SubsamplingScaleImageView的时候关闭Config.SWIPE_DISMISS

确实是设置了 SUBSAMPLING_SCALE_TYPE 为 SCALE_TYPE_START，设成 SCALE_TYPE_CENTER_INSIDE 达不到想要的效果，最后还是改为 当当前页面为SubsamplingScaleImageView的时候关闭Config.SWIPE_DISMISS

**Comment by iielse** [comment]
当时做的时候init Scale 逻辑没接好. 我后面有时间会再看下Subsampling View 源码. 能不能实时拿到图片当前的状态. 有没有到顶 或到底 什么的.  如果能拿到 还可以优化

**Comment by iielse** [comment]
因为有很多细节，比如video模块，还有一些配置，这一块都是灵活的，而demo是需要将他们全部展示出来的。所以集成的时候，可能拉进项目的代码只有30%不到。😂

**Comment by iielse** [comment]
那个区块加载的库， 没有舒服的回调， 怎么搞

**Comment by iielse** [comment]
突然有个想法， 有时间尝试一下

**Comment by iielse** [comment]
@bytebubbles 老哥还在吗？ 帮忙看下最新代码的下拉效果 是否ok ?

**Comment by bytebubbles** [comment]
@iielse 现在没用这个了，你看一下吧，后面用到了我再看看

**Comment by iielse** [comment]
👌

**Comment by iielse** [comment]
自测已修复。 默认展示长图顶部内容
