### ISSUE TITLE
第一次点击图片时，由于需要通过网络下载图片，没有界面过渡动画

### ISSUE THREAD

**Issue by githubliangzai** [iielse/imageviewer#124]
第一次点击图片时，由于需要通过网络下载图片，就没有界面过渡动画，如果网络不好，大图界面会显示一片黑比较久，但是如果我加载图片的时候设置placeholder，此时有过渡动画，但是过渡效果会闪一下

**Comment by iielse** [comment]
麻烦贴下效果.和你的加载会闪的代码 .

**Comment by githubliangzai** [comment]
demo代码 MyImageLoader中通过Glide加载图片时设置占位图，不使用缓存来模拟第一次加载图片，过渡动画会有闪烁
![image](https://user-images.githubusercontent.com/12453412/126733787-b063e662-4141-48fc-bc56-f53f082a64a9.png)

**Comment by iielse** [comment]
这里的load在加载第一张时会触发2次.具体见 https://github.com/iielse/imageviewer/issues/99

开发者在第一次load的时候实时提供缩略图给ImageView即可.

**Comment by githubliangzai** [comment]
![image](https://user-images.githubusercontent.com/12453412/127083177-b8efb64f-9e5b-44aa-829b-b4add3917d40.png)
![image](https://user-images.githubusercontent.com/12453412/127083197-f9c4f978-5bd8-4a74-a145-5616a992a46c.png)
上面是我按照大佬的demo使用的代码，但是网络比较卡的情况下第一次点击打开大图时没有过渡动画，表现为大图页显示黑屏，过来一会儿，大图直接加载出来

**Comment by githubliangzai** [comment]
![image](https://user-images.githubusercontent.com/12453412/127083911-5259523f-7501-40c8-8406-b9135270d111.png)
我现在用这样的方式来规避问题

**Comment by iielse** [comment]
试下

```
Glide.with(view).load(it)
        .placeholder(view.drawable ?: getDrawable(R.mipmap.placeholder))
        .into(view)
```

**Comment by githubliangzai** [comment]
Glide.with(view).load(it)
        .placeholder(view.drawable ?: getDrawable(R.mipmap.placeholder))
        .into(view)
这个我试过，第一次加载图片的时候，如果网络较慢，过渡动画开始时，图片显示的是占位图，这个没问题，但是如果在过渡动画结束前，如果图片加载成功了，这个时候动画中的PhotoView2的会显示加载成功的图片，但是图片突然变得很大，直到最后动画执行完才回复到正常大小

**Comment by iielse** [comment]
```
Glide.with(view).load("")
            .apply { if(view.drawable == null) override(thumbnailImageSize, thumbnailImageSize) }
            .placeholder(view.drawable ?: getDrawable(R.mipmap.placeholder))
            .into(view)
```

预览加载的时候 固定size试试

**Comment by githubliangzai** [comment]
不行额

**Comment by iielse** [comment]
大图界面的loading 请这样加 https://github.com/iielse/imageviewer/issues/115
。
是的其实不需要占位图的。
