### ISSUE TITLE
线上崩溃java.lang.IllegalStateException  Fragment FullScreenImageViewerDialogFragment{2998a4f} (e029c2a1-c25e-4b63-a883-22f4197f941f) not associated with a fragment manager.

### ISSUE THREAD

**Issue by githubliangzai** [iielse/imageviewer#125]
# main(1)

java.lang.IllegalStateException

Fragment FullScreenImageViewerDialogFragment{2998a4f} (e029c2a1-c25e-4b63-a883-22f4197f941f) not associated with a fragment manager.

解析原始
1
androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1040)
2
androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:350)
3
androidx.fragment.app.DialogFragment.dismissAllowingStateLoss(DialogFragment.java:317)
4
com.github.iielse.imageviewer.utils.TransitionEndHelper$end$doTransition$1$1$1.onTransitionEnd(TransitionEndHelper.kt:34)
5
androidx.transition.Transition.end(Transition.java:1952)
6
androidx.transition.TransitionSet$TransitionSetListener.onTransitionEnd(TransitionSet.java:451)
7
androidx.transition.Transition.end(Transition.java:1952)
8
androidx.transition.Transition$3.onAnimationEnd(Transition.java:1901)
9
android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
10
android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1242)
11
android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1484)
12
android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
13
android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
14
android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
15
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1055)
16
android.view.Choreographer.doCallbacks(Choreographer.java:875)
17
android.view.Choreographer.doFrame(Choreographer.java:772)
18
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
19
android.os.Handler.handleCallback(Handler.java:888)
20
android.os.Handler.dispatchMessage(Handler.java:100)
21
android.os.Looper.loop(Looper.java:213)
22
android.app.ActivityThread.main(ActivityThread.java:8178)
23
java.lang.reflect.Method.invoke(Native Method)
24
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
25
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by iielse** [comment]
可能使用了Handler.post等异步操作.没有注意生命周期的关联.内容不足.只能暂时分析到这里了.

**Comment by iielse** [comment]
bug 我这边 复现了，应该找到原因了， 马上解决

**Comment by iielse** [comment]
implementation 'com.github.iielse:imageviewer:2.1.8'

试下这个

**Comment by githubliangzai** [comment]
大佬威武

**Comment by iielse** [comment]
怎么样了，小哥，还有吗

**Comment by iielse** [comment]
有问题再打开

**Comment by githubliangzai** [comment]
没有再发现崩溃了

**Comment by iielse** [comment]
ok
