### ISSUE TITLE
希望能合并viewer_remove_item分支，开放移除api

### ISSUE THREAD

**Issue by liamyu** [iielse/imageviewer#127]
如题，不能移除就很难，现在是引入源码自己改的，但是改了以后后续升级又不方便

**Comment by iielse** [comment]
好的， 我看下

**Comment by iielse** [comment]
viewer_remove_item 分支更新了

**Comment by iielse** [comment]
implementation 'com.github.iielse:imageviewer:2.1.10'

ImageViewerActionViewModel  remove.

@liamyu

**Comment by iielse** [comment]
若还有问题再打开
