### ISSUE TITLE
大佬，能不能给个java版的

### ISSUE THREAD

**Issue by xuecq236** [iielse/imageviewer#129]
项目之前一直用的是1.1.5版本，最近突然来了一批大图，得加载本地分辨较高的大图片，就发现了问题，没怎么用过kotlin。。。

**Comment by iielse** [comment]
我也觉得 demo 好像有点复杂， 我看下有没有可以简化的地方， 近段时间有时间会搞一下的

**Comment by xuecq236** [comment]
对，可不可以搞一些默认的设置，使用的时候直接传入就能看到效果比如List<url>、List<Uri>、url、Uri这种

**Comment by iielse** [comment]
你看 CustomTransitionHelper.show .  这就是最简单的写法了

**Comment by iielse** [comment]
@xuecq236 能简化的都简化了，看下readme的集成流程 配合demo代码

**Comment by xuecq236** [comment]
嗯嗯，按照demo做了，方便加个企鹅嘛，有些问题。。

**Comment by iielse** [comment]
517309507。 java demo 就不补了

**Comment by iielse** [comment]
若还有问题再打开
