### ISSUE TITLE
超长图大图预览时，遇到个问题

### ISSUE THREAD

**Issue by zhangkun0018** [iielse/imageviewer#134]
超长图大图预览时，设置为SubsamplingScaleImageView.SCALE_TYPE_CENTER_INSIDE模式时，图片不显示。触摸之后，图片才会显示出来。
https://user-images.githubusercontent.com/23331766/183039852-4e7403db-6fd2-45f8-b7e8-99a8460c08d0.mp4

**Comment by iielse** [comment]
你说的问题我前段时间遇到过 。最近前一次修改，我对SubsamplingScaleImageView的逻辑调整过，支持了下拽返回。 开发者不需要再设置  SubsamplingScaleImageView 的 scaleType 了。 你看下你这里用的[2.1.16]吗

**Comment by zhangkun0018** [comment]
我用的不是最新的，我换最新的试试

**Comment by zhangkun0018** [comment]
我现在需要设置SubsamplingScaleImageView.SCALE_TYPE_CENTER_INSIDE模式，用2.1.16也还是会出现上面的问题。

**Comment by iielse** [comment]
你看下最新的demo代码。 SubsamplingScaleImageView的scaleType我这边应该已经做成禁止设置的了。 然后同时支持了下拽返回。最新的代码应该也不存在开始是黑屏要触碰一下才显示内容的问题

**Comment by zhangkun0018** [comment]
最新版本2.1.16 SubsamplingScaleImageView的scaleType是SubsamplingScaleImageView.SCALE_TYPE_START没有问题，但是我想要的是，默认加载SubsamplingScaleImageView的scaleType是SubsamplingScaleImageView.SCALE_TYPE_CENTER_INSIDE就不行。

**Comment by iielse** [comment]
现在不需要在关心 SCALE_TYPE_CENTER_INSIDE 这种模式吧。
