### ISSUE TITLE
使用该库一堆冲突 implementation 'com.davemorrissey.labs:subsampling-scale-image-view:3.10.0'

### ISSUE THREAD

**Issue by xuxinjiang** [iielse/imageviewer#136]
使用该库一堆冲突 implementation 'com.davemorrissey.labs:subsampling-scale-image-view:3.10.0'

**Comment by iielse** [comment]
https://github.com/davemorrissey/subsampling-scale-image-view/releases/tag/v3.10.0.  这个是他的最新版本.  你的具体冲突错误信息是什么？   为什么demo没有冲突呢？

**Comment by iielse** [comment]
长时间未回复
