### ISSUE TITLE
希望能优化横屏的缩放过渡动画

### ISSUE THREAD

**Issue by TwilightKHQ** [iielse/imageviewer#146]
版本：2.1.21
问题：将Demo中的MainActivity固定横屏展示后，图片的缩放动画起始位置有一定的偏移，并不能完全对应上。
因为有产品需要一直保持横屏使用，所以希望能优化一下。

![uTools_1680245222019](https://user-images.githubusercontent.com/25874642/229044301-e8f916ce-8dde-4f9e-83d6-94fa1e0d49b9.png)
![uTools_1680245165165](https://user-images.githubusercontent.com/25874642/229044318-5274fdee-342e-4a4e-afa4-a13396a6c939.png)

**Comment by iielse** [comment]
step1:更新sdk至：2.1.22
step2:清单文件增加 android:screenOrientation="landscape"
step3:在Activity onCreate方法中增加 Config.TRANSITION_OFFSET_X = statusBarHeight

**Comment by TwilightKHQ** [comment]
补充一下，横屏状态下需要同时考虑水平方向的刘海高度和垂直方向的状态栏高度

```
Config.TRANSITION_OFFSET_Y = 状态栏高度
Config.TRANSITION_OFFSET_X = 刘海高度
```
