### ISSUE TITLE
请教一个问题，大图怎么延伸到状态栏上面呢

### ISSUE THREAD

**Issue by twlk-jzy** [iielse/imageviewer#148]

**Comment by iielse** [comment]
@twlk-jzy  参考@1wayticket的实现，将图片放大依赖的activity页面布局延伸到状态栏  https://github.com/iielse/imageviewer/issues/103

**Comment by 1wayticket** [comment]
Application或者第一个Activity入口处设置：
Config.INSTANCE.setTRANSITION_OFFSET_Y(BarUtils.getStatusBarHeight(this));

**Comment by wyy-dev** [comment]
我用demo测试权限也没有生效
