### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by CK875430315** [iielse/imageviewer#149]
大佬你好，androidstudio检测到ImageViewerDialogFragment里面有内存泄漏。。会不会是viewerHandler引起的？
![C468A96D-56B7-44ed-868B-BA4077007ADC](https://github.com/iielse/imageviewer/assets/13899092/3aec0fa2-8e78-491e-8627-c35dd7570aa7)

**Comment by CK875430315** [comment]
![C468A96D-56B7-44ed-868B-BA4077007ADC](https://github.com/iielse/imageviewer/assets/13899092/816627c0-2576-44e1-8025-20f895bf8bad)

**Comment by iielse** [comment]
看下引用持有者是谁。 viewerHandler代码里面没看出来。可以继续展开箭头看看

**Comment by CK875430315** [comment]
> 看下引用持有者是谁。 viewerHandler代码里面没看出来。可以继续展开箭头看看
![3](https://github.com/iielse/imageviewer/assets/13899092/ca89870d-e1b1-47e3-a2ff-b40c1071b45f)

全部展开了，但是也只是猜测是handler

**Comment by CK875430315** [comment]
> 看下引用持有者是谁。 viewerHandler代码里面没看出来。可以继续展开箭头看看

太深奥看不懂，算了，关了。
