### ISSUE TITLE
请问拖拽的时候我想让底部页面的图片消失(alpha=0)，该如何实现

### ISSUE THREAD

**Issue by yptang97** [iielse/imageviewer#151]
我在Demo实践：在动画开始时设置了startView的alpha为0,动画结束(时机为`TransitionEndHelper.onTransitionEnd`)恢复alpha=1，退出动画不符合预期，表现为过渡动画View先消失了startView才显示 会有短暂的空白缺失，其他白色块是网络原因加载不到图片 忽略。且目前库代码也没有增加动画回调的入口，期待支持~

https://github.com/iielse/imageviewer/assets/77526669/393c2b0c-3f48-40ef-ad3a-f6924e7ea557

**Comment by iielse** [comment]
实现ImageViewerBuilder.setViewerFactory这样你就能监听ImageViewerDialogFragment的生命周期;
TransitionEndHelper.end方法最终会调用ImageViewerDialogFragment实例的dismissAllowingStateLoss方法;  
将dismissAllowingStateLoss这里作为动画结束的时机；重写这个方法这里增加你的自定义代码

**Comment by iielse** [comment]
实现ViewerCallback接口的onRelease方法. 根据 DURATION_TRANSITION 的值来设置延迟任务恢复你的View显示; 比如假设 DURATION_TRANSITION = 300 则你可以在270毫秒的时刻恢复
