### ISSUE TITLE
SubsamplingScaleImageView  使用问题

### ISSUE THREAD

**Issue by TonyGJJ** [iielse/imageviewer#153]
图片地址：
https://cdn4.shanhs.com/offline-upload/pro/20231225/31c953be738447aa8fdfaae7be20d516.jpg?x-oss-process=image/resize,l_4000,image/format,webp

这是一张比较大的图 我使用了 Subsampling 来显示。但是这个默认会显示全屏，但是我希望的是普通Photo 的样式，在中间居中显示。

**Comment by iielse** [comment]
关于 SubsamplingScaleImageView 你可以尝试使用 setMinimumScaleType 来控制默认显示方案
