### ISSUE TITLE
没有过度动画，SimpleTransformer的getView方法返回null

### ISSUE THREAD

**Issue by yuxiaoye1223** [iielse/imageviewer#154]
SimpleTransformer的put方法没有调用，导致getView方法返回的一直是null，请问这个put方法应该在什么地方调用呢？

**Comment by yuxiaoye1223** [comment]
> SimpleTransformer的put方法没有调用，导致getView方法返回的一直是null，请问这个put方法应该在什么地方调用呢？

参考了demo中的方法，在Adapter的onViewAttachedToWindow中增加了put调用。

但是有一个问题，onViewAttachedToWindow比Create晚，存在时序问题，我手动处理了一下好了。

大佬能否在readme中增加一下提示

**Comment by iielse** [comment]
我最近看了下。实际上使用我这个项目的一般都是8-15年的老鸟了。很多问题看两眼，懂的都懂。

**Comment by iielse** [comment]
```
transition[imageView] = photoId
imageView.addOnAttachStateChangeListener(object : View.OnAttachStateChangeListener {
    override fun onViewAttachedToWindow(p0: View?) {
        transition[imageView] = photoId
    }
    override fun onViewDetachedFromWindow(p0: View?) {
        transition.remove(imageView)
        imageView.removeOnAttachStateChangeListener(this)
    }
})
```
这样可能就能跑了
