### ISSUE TITLE
自定义 IndexProvider 中 点击事件不触发

### ISSUE THREAD

**Issue by Sforllln** [iielse/imageviewer#39]
`            new ImageWatcher.IndexProvider() {
                    private View view;

                    @Override
                    public View initialView(Context context) {
                        FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT,
                                MyUtils.dip2px(context, 40));//
                        lp.gravity = Gravity.BOTTOM | Gravity.CENTER_HORIZONTAL;
                        view = LayoutInflater.from(context).inflate(R.layout.image_index, null);
                        view.setLayoutParams(lp);
                        return view;
                    }

                    @Override
                    public void onPageChanged(final ImageWatcher imageWatcher, int position, List<Uri> list) {
                        TextView textIndex = view.findViewById(R.id.tv_index);
                        TextView tvShare = view.findViewById(R.id.tv_share);
                        textIndex.setText(String.format("%s/%s", position + 1, list.size()));
                        tvShare.setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                ToastUtils.show("分享");
                            }
                        };`

**Comment by Sforllln** [comment]
能否指点一下 @iielse

**Comment by Sforllln** [comment]
了解  可以考虑为这个 "索引" View 保留一下点击事件

**Comment by iielse** [comment]
我正在改这里，

**Comment by iielse** [comment]
改好了， /doge

**Comment by iielse** [comment]
这里看你代码是想分享吧？ 可以考虑实现图片长按回调。  然后在底部弹出框， 上面带一个分享按钮这样

**Comment by iielse** [comment]
你看下 demo1 里面那种图片长按后的方式可以吗

**Comment by Sforllln** [comment]
好的 谢谢你  就用长按实现吧 ,昨天太忙了 没有回复你

**Comment by iielse** [comment]
没有 主要还是我太菜了

**Comment by Sforllln** [comment]
我也尝试 down下来改过 没搞定  -,-

**Comment by iielse** [comment]
我搞了，上一次提交ok的。但是别的功能挂了。所以放弃了。反正显示隐藏,滑动位置的回调都给出去了，你可以在 `ImageWatcher`的上面放`View`这样就不会截掉你的事件了

**Comment by Sforllln** [comment]
主要还是我太菜 - -, 其实长按也挺好的,但是加个View 可以做更多的事

**Comment by Sforllln** [comment]
感觉还有一点可以优化 就是View 在拖动的时候 把 IndexProvider 这个View 隐藏掉

**Comment by Tecrafter** [comment]
我这边需要在 ViewPager 下加个横向列表预览，老哥你说这 IndexProvider 的事件该怎么加才好。。

**Comment by iielse** [comment]
看下demo2  otherView

**Comment by Sforllln** [comment]
老哥 666

**Comment by iielse** [comment]
感觉还有一点可以优化 就是View 在拖动的时候 把 IndexProvider 这个View 隐藏掉
