### ISSUE TITLE
9宫格 gif

### ISSUE THREAD

**Issue by wangtao2855** [iielse/ImageViewer#49]
9宫格里面图片展示,是不支持gif嘛?,为什么我放入了一个gif,显示错乱

**Comment by iielse** [comment]
因为`drawable` 用的是同一个对象。start被调用2次导致的错乱吧。

9宫格里面最好是 静态的 再在右下角提供动图标志。 个人觉得这样最合理了。

**Comment by iielse** [comment]
这个问题好像可以解决， 我记住了

**Comment by wangtao2855** [comment]
> 这个问题好像可以解决， 我记住了

自定义一个ImageView就OK了

**Comment by iielse** [comment]
@wangtao2855 我改好了应该，你要不看下，demo2里面 九宫格初始都是gif， 没有显示错乱了 现在。
