### ISSUE TITLE
imageview 使用 fixxy 图片缩小的问题

### ISSUE THREAD

**Issue by silence-jianghuan** [iielse/imageviewer#51]
imageview 使用 fixxy以后，息屏再打开，图片会缩小至大概四分之一，出现在控件的左上角。

**Comment by iielse** [comment]
我在demo3里面加了个imageView 设置scaleType是fitXY.点开查看大图后，息屏再打开，没有出现你说的问题。是正常的。

**Comment by iielse** [comment]
框架重构后基于PhotoView. 且adapter的动画初始化只会执行一次. 
请尝试使用 `ImageViewerBuilder.show` 来展示数据
