### ISSUE TITLE
在fragment里的viewpager里的Fragment(FragmentStatePagerAdapter)用只显示小图或者不显示

### ISSUE THREAD

**Issue by nicelyjust** [iielse/ImageViewer#52]
按照demo6用的-->
iwHelper.show(i , imageGroupList ,urlList);显示小图;
iwHelper.show(urlList);这样不显示;
logcat,没有显示错误.

**Comment by iielse** [comment]
问题同 https://github.com/iielse/ImageViewer/issues/73 一致
