### ISSUE TITLE
一张图片显示,会变形MessagePicturesLayout

### ISSUE THREAD

**Issue by nicelyjust** [iielse/ImageViewer#56]

**Comment by iielse** [comment]
有变形的样子吗，贴一下给我参考下吧

**Comment by nicelyjust** [comment]
例如一张图片的原比例是4:3，显示是1:1所以就会变形




| |
李增
|
|
邮箱：nicely_email@yeah.net
|

签名由 网易邮箱大师 定制

在2018年11月12日 16:02，else 写道：

有变形的样子吗，贴一下给我参考下吧

**Comment by nicelyjust** [comment]
建议加个图片宽高比例


| |
李增
|
|
邮箱：nicely_email@yeah.net
|

签名由 网易邮箱大师 定制

在2018年11月12日 16:02，else 写道：

有变形的样子吗，贴一下给我参考下吧

**Comment by iielse** [comment]
[NineGridView](https://github.com/KCrason/HighPerformanceFriendsCircle/blob/master/app/src/main/java/com/kcrason/highperformancefriendscircle/widgets/NineGridView.java)

使用它来替代`MessagePicturesLayout `是非常好的选择.
