### ISSUE TITLE
Fragment+BottomBar配合使用问题

### ISSUE THREAD

**Issue by Vicent9920** [iielse/imageviewer#57]
通过重写 ImageWatcher 的 show 和 onSingleTapConfirmed 方法来实现图片展示与关闭的回调。在使用过程中，发现图片右下角黑屏处点击会回调 onSingleTapConfirmed 方法而没有关闭图片，请问这个异常有解决方案吗？

**Comment by iielse** [comment]
是不是还有 触摸图片无反应 等现象。如果是这样：
```
final SparseArray<ImageView> mappingViews = new SparseArray<>();
mappingViews.put(0, (ImageView) v);
iwHelper.show((ImageView) v, mappingViews, convert(longPictureList));
```
这里面第二行代码有个 `0` ，这个参数设置 是默认图片位置，如果设错了就会有这些问题。

如何设置默认图片在第n个位置：
比如你加载的图片url值是 abc，那这里的下标就用 longPictureList.indexOf(abc)

**Comment by Vicent9920** [comment]
没有你说的问题，只有我上面遇到的点击右下角（不是挨着右边，有一点点距离）会回调onSingleTapConfirmed 方法，但是页面并没有关闭。我的使用方法是常规的：

`
void show(ImageView i, List<ImageView> imageGroupList, final List<String> urlList) 
`

**Comment by iielse** [comment]
可能你正在使用的版本是之前的，之前的版本有问题。
现在show 的 api 就2个。

`public void show(ImageView i, SparseArray<ImageView> imageGroupList, List<Uri> urlList)`

`public void show(List<Uri> urlList)`

**Comment by iielse** [comment]
新版本ImageViewer是使用Dialog来实现的.
关闭页面的处理交给了系统的物理返回键.以及’下拽退出’手势的判定.
