### ISSUE TITLE
请问 recyclerview的item中含有文字和图片, 图片, 我再下拉重新重新刷新时 所有图片都不显示, 返回重新进入,图片也不现实,  加载更多刷新适配器后图片有的不显示并且item图片错乱, 这是什么情况

### ISSUE THREAD

**Issue by kouqinghua** [iielse/imageviewer#61]

**Comment by kouqinghua** [comment]
该情况该如何解决 谢谢

**Comment by DuShuYuan** [comment]
不知道咱俩的问题是不是一样的，我这的现象是第一次进入9宫格显示，finish之后再进入就不显示了，然后下拉刷新一下就显示了（只有9宫格不显示，其他头像文字正常），或者跳到其他页面再回来也会显示9宫格，然后始终都是finish之后再进入就不显示

**Comment by DuShuYuan** [comment]
> 不知道咱俩的问题是不是一样的，我这的现象是第一次进入9宫格显示，finish之后再进入就不显示了，然后下拉刷新一下就显示了（只有9宫格不显示，其他头像文字正常），反正始终都是finish之后再进入就不显示

解决办法：glide只使用硬盘缓存，skipMemoryCache(true)//跳过内存缓存

**Comment by kouqinghua** [comment]
> 不知道咱俩的问题是不是一样的，我这的现象是第一次进入9宫格显示，finish之后再进入就不显示了，然后下拉刷新一下就显示了（只有9宫格不显示，其他头像文字正常），反正始终都是finish之后再进入就不显示

你下拉刷新和加载更多有问题吗

**Comment by iielse** [comment]
你们都是 demo2 出得这个问题吗？ 很抱歉，我现在没能复现这个

**Comment by kouqinghua** [comment]
> 你们都是 demo2 出得这个问题吗？ 很抱歉，我现在没能复现这个

demo1, 望做下下拉刷新, 上拉加载, 页面返回退出重新进入页面, 谢谢, 现在正需要该需求

**Comment by Ronadlo7** [comment]
我也遇到了，滑到下面，再来刷新的时候，图片显示就错乱了

**Comment by laiyadianzi** [comment]
> 不知道咱俩的问题是不是一样的，我这的现象是第一次进入9宫格显示，finish之后再进入就不显示了，然后下拉刷新一下就显示了（只有9宫格不显示，其他头像文字正常），反正始终都是finish之后再进入就不显示

我和你这个差不多，但是我是tab+viewpager ，我切换后tab后九宫格就不显示了，下拉刷新下就显示，skipMemoryCache(true)会有个notification有闪烁的情况，体验也不太好

**Comment by iielse** [comment]
我大胆的猜测了一下. 可能是点击查看大图.在加载大图前,直接使用了缩略图的Drawable对象导致的. 而且动态图出问题几率比较大?(我看了其他框架里面会把原始图copy一份)

**Comment by iielse** [comment]
这个bug可能是我很久以前实现transition动画直接使用了缩略图的drawable对象导致的。。这段时间，我将代码重构了一次，并且添加了常用的recyclerView 的demo。 请你们试一试。
