### ISSUE TITLE
适配RTL问题

### ISSUE THREAD

**Issue by EKwongChum** [iielse/imageviewer#63]
ImageWatcherHelper类的show()之后，回归位置不对。
在阿语或希伯来语环境有问题，图片回归时直接往屏幕右边飞过去了。
能否进行RTL适配呢？

**Comment by iielse** [comment]
好的。 我会在ImageViewer中添加尝试修复这个问题

**Comment by iielse** [comment]
2.0.6 我用阿拉伯语言测试过,应该好了
