### ISSUE TITLE
缩略图问题

### ISSUE THREAD

**Issue by lnl1314abm** [iielse/imageviewer#68]
查看大图的时候，先展示的那个缩略图能不能默认放大到全屏？微信就是那样，并不是缩略图有好大就显示好大

**Comment by yuxingxing1988** [comment]
@lnl1314abm大佬  这个问题你搞好了没？

**Comment by yuxingxing1988** [comment]
> 查看大图的时候，先展示的那个缩略图能不能默认放大到全屏？微信就是那样，并不是缩略图有好大就显示好大
大佬这个问题你搞好了没？

**Comment by iielse** [comment]
那样形状发生变化的的渐变效果不好吧

**Comment by yuxingxing1988** [comment]
@iielse  可以看看微信朋友圈的效果

**Comment by jijingtaifeng** [comment]
大佬这个问题有解决的没，我弄了下，效果不是太好

**Comment by iielse** [comment]
查看大图的时候，先展示的那个缩略图能不能默认放大到全屏？微信就是那样，并不是缩略图有好大就显示好大
——————————————————
现在框架的图片展示基于 `PhotoView` 一开始图片展示尺寸便会放大为全屏
使用 `ImageViewerBuilder.show()` 来展示数据
