### ISSUE TITLE
缩略图显示比较大的时候 预览的位置不居中

### ISSUE THREAD

**Issue by Vanrevfront** [iielse/imageviewer#69]
缩略图显示比较大的时候 预览的位置不居中 另外建议增加到Activity 和上滑关闭图片预览
![3ec13a7c8e7f1ce4c23d303746f603d](https://user-images.githubusercontent.com/18024185/50811477-751ebd80-1349-11e9-94b1-a7dd7ef6fddc.jpg)
![b72b64750bad97735a4e284e4167199](https://user-images.githubusercontent.com/18024185/50811478-794adb00-1349-11e9-9283-b2f3cb27d6f1.jpg)

**Comment by cultivation-of-taoism** [comment]
我也碰到这样问题，希望作者尽快修复

**Comment by iielse** [comment]
现在框架的图片展示基于 `PhotoView`  :)
请尝试使用 `ImageViewerBuilder.show()` 来展示数据
