### ISSUE TITLE
如何在代码中关闭viewpager?

### ISSUE THREAD

**Issue by Bert0324** [iielse/imageviewer#70]
关闭当前浏览的照片

**Comment by equationl** [comment]
有同样的需求，没发现作者有预留接口
可以参考一下，我是用模拟点击返回键来退出的：
`try {
   Runtime.getRuntime().exec("input keyevent "+KeyEvent.KEYCODE_BACK);
       } catch (Exception e) {}`

这是作者的退出代码：
` /**
     * 处理结束下拉退出的手指事件，进行退出图片查看或者恢复到初始状态的收尾动画<br>
     * 还需要还原背景色
     */
    private void handleExitTouchResult() {
        if (iSource == null) return;

        if (mExitRef > 0.75f) {
            ViewState vsExit = ViewState.read(iSource, ViewState.STATE_EXIT);
            if (vsExit != null) animSourceViewStateTransform(iSource, vsExit);
            animBackgroundTransform(0xFF000000, 0);
        } else {
            ViewState vsOrigin = ViewState.read(iSource, ViewState.STATE_ORIGIN);
            if (vsOrigin != null) {
                if (vsOrigin.alpha == 0) {
                    vsOrigin.translationX(iSource.getTranslationX()).translationY(iSource.getTranslationY());
                }
                animSourceViewStateTransform(iSource, vsOrigin);
            }

            animBackgroundTransform(0x00000000, STATE_EXIT_HIDING);
            ((FrameLayout) iSource.getParent()).getChildAt(2).animate().alpha(0).start();
        }
    }`

**Comment by iielse** [comment]
主动调用 `iwHelper.handleBackPressed()`  `imageWatcher.handleBackPressed() ` 可以吗？

**Comment by equationl** [comment]
> 主动调用 `iwHelper.handleBackPressed()` `imageWatcher.handleBackPressed() ` 可以吗？

额，没有试过欸

**Comment by iielse** [comment]
已为 `ImageViewerActionViewModel`  追加 `dismiss`方法来主动关闭当前浏览照片
可以使用 `ImageViewerBuilder.show()` 来展示你的数据
