### ISSUE TITLE
使用ConstraintLayout嵌套 图片第一次加载不出来

### ISSUE THREAD

**Issue by Haveotom** [iielse/ImageViewer#75]
使用ConstraintLayout嵌套 图片第一次加载不出来，多滑动几次界面，图片才能显示，而且会出现图片错乱的情况。

**Comment by iielse** [comment]
第一个问题同 https://github.com/iielse/ImageViewer/issues/73

第二个问题同 https://github.com/iielse/ImageViewer/issues/61
