### ISSUE TITLE
点击放大时动画问题

### ISSUE THREAD

**Issue by Little-Ann** [iielse/ImageViewer#77]
点击放大时，有时会有动画从屏幕中间开始展开， 有时直接从点击的地方展开， 是什么原因？测试对这个揪着不放可咋整呢
![image](https://user-images.githubusercontent.com/6840006/55237180-7e466900-526c-11e9-812d-aa0e20740ec9.png)
![image](https://user-images.githubusercontent.com/6840006/55237192-8a322b00-526c-11e9-8c75-84b35b5396a1.png)
这个图片能看到吗？？

**Comment by gebaobao** [comment]
图片没有加载出来会是图1情况Glide onResourceReady方法中才会设置图片放大

**Comment by Little-Ann** [comment]
> 图片没有加载出来会是图1情况Glide onResourceReady方法中才会设置图片放大

谢谢回复，哈哈哈~~（不过我已经离开这个公司了）

**Comment by iielse** [comment]
问题同 https://github.com/iielse/ImageViewer/issues/68
