### ISSUE TITLE
ViewPager中的RecyclerView列表中的图片，ViewPager切换后图片变白

### ISSUE THREAD

**Issue by XuQK** [iielse/imageviewer#80]
ViewPager中RecyclerView列表，里面的图片，点击`image_1`调用`iwHelper.show()`方法显示大图，然后退出大图后，ViewPager跳到非相邻的页面，比如在`fragment_1`里浏览的大图，然后跳到`fragment_3`，再跳回`fragment_1`，此时之前浏览的列表中的`image_1`变成空白了，需要切到后台再切回来，或者上下滑动滑出列表再滑回来才显示。这可能是为什么呢？
我是用Fresco加载的图片，写法照抄您的demo

**Comment by iielse** [comment]
问题可能同 https://github.com/iielse/ImageViewer/issues/61
