### ISSUE TITLE
列表超过屏幕  有的图片加载不出来

### ISSUE THREAD

**Issue by chengmenghuiAndroid** [iielse/ImageViewer#84]

**Comment by chengmenghuiAndroid** [comment]
我建议 在MessagePicturesLayout类加载图片哪里增加方法
 mRecyclerView.addOnScrollListener(getListener(thumbList, i, iPicture));
避免滑动过程中加载图片失败 ，直接滑动停止后加载图片；
这里为了避免重复设置增加开销，设置了一个sIsScrolling 标志变量来做判断。
/**
     * RecyclerView 滑动时不让 Glide 加载图片
     * @param thumbList
     * @param i
     * @param iPicture
     * @return  
     */
    private RecyclerView.OnScrollListener getListener(final List<Uri> thumbList, final int i, final ImageView iPicture) {
        return new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                if (newState == RecyclerView.SCROLL_STATE_IDLE) {
                    sIsScrolling = true;
                    Glide.with(getContext()).resumeRequests();//恢复Glide加载图片
                    Glide.with(getContext()).load(thumbList.get(i)).into(iPicture);
                    Log.e("MessageAdapter----", "RecyclerView停止滑动");

                } else {
                    if (sIsScrolling = true) {
                        Glide.with(getContext()).pauseRequests();//禁止Glide加载图片
                        Log.e("MessageAdapter----", "RecyclerView滑动中");
                    }
                    sIsScrolling = false;
                }
            }
        };
    }

**Comment by chengmenghuiAndroid** [comment]
我建议 在MessagePicturesLayout类加载图片哪里增加方法
mRecyclerView.addOnScrollListener(getListener(thumbList, i, iPicture));
避免滑动过程中加载图片失败 ，直接滑动停止后加载图片；
这里为了避免重复设置增加开销，设置了一个sIsScrolling 标志变量来做判断。
/**
* RecyclerView 滑动时不让 Glide 加载图片
* @param thumbList
* @param i
* @param iPicture
* @return
*/
private RecyclerView.OnScrollListener getListener(final List thumbList, final int i, final ImageView iPicture) {
return new RecyclerView.OnScrollListener() {
@override
public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
if (newState == RecyclerView.SCROLL_STATE_IDLE) {
            sIsScrolling = true;
           Glide.with(getContext()).resumeRequests();//恢复Glide加载图片
          Glide.with(getContext()).load(thumbList.get(i)).into(iPicture);
          Log.e("MessageAdapter----", "RecyclerView停止滑动");
            } else {
                if (sIsScrolling = true) {
                    Glide.with(getContext()).pauseRequests();//禁止Glide加载图片
                    Log.e("MessageAdapter----", "RecyclerView滑动中");
                }
                sIsScrolling = false;
            }
        }
    };
}

**Comment by iielse** [comment]
对于`MessagePicturesLayout` 当时的设计定位只是为了在Demo中演示常见的'9宫格'效果,实现方案比较粗糙.

[NineGridView](https://github.com/KCrason/HighPerformanceFriendsCircle/blob/master/app/src/main/java/com/kcrason/highperformancefriendscircle/widgets/NineGridView.java)

使用它来替代`MessagePicturesLayout `是不错的选择.
