### ISSUE TITLE
otherview 是起什么作用的，没看懂

### ISSUE THREAD

**Issue by laiyadianzi** [iielse/imageviewer#89]

**Comment by iielse** [comment]
这个命名不够友好.应该为`OverlayView`类似的概念
用来在Viewer上层做一些ui展示， 如指示器显示 同 https://github.com/iielse/ImageViewer/issues/39
现框架重构了，解决了 超大图加载痛点
使用 `ImageViewerBuilder.show()` 来展示数据吧
