### ISSUE TITLE
在dialog显示的时候，从dialog弹出预览图，显示在dialog的后面，这个新版本kotlin解决了是吗？

### ISSUE THREAD

**Issue by henryneu** [iielse/imageviewer#92]
在dialog显示的时候，从dialog弹出预览图，显示在dialog的后面，这个新的kotlin版本解决了是吗？老版本Java的不支持是吧？能沟通一下不？不太懂kotlin，想请教一下思路，改造一下Java版本的

**Comment by iielse** [comment]
这个新的kotlin版本解决了是吗？

**Comment by henryneu** [comment]
好的，多谢回复，我尝试一下
