### ISSUE TITLE
希望可以封装禁止录屏/截屏功能

### ISSUE THREAD

**Issue by JingweiWang** [iielse/imageviewer#93]

**Comment by iielse** [comment]
如果我理解的没错的话你可以尝试

```
builder.setViewerCallback(object : ViewerCallback {
    override fun onInit(viewHolder: RecyclerView.ViewHolder) {
        activity?.window?.addFlags(WindowManager.LayoutParams.FLAG_SECURE)
    }

    override fun onRelease(viewHolder: RecyclerView.ViewHolder, view: View) {
        activity?.window?.clearFlags(WindowManager.LayoutParams.FLAG_SECURE)
    }
})
```

**Comment by JingweiWang** [comment]
> 如果我理解的没错的话你可以尝试
> 
> ```
> builder.setViewerCallback(object : ViewerCallback {
>     override fun onInit(viewHolder: RecyclerView.ViewHolder) {
>         activity?.window?.addFlags(WindowManager.LayoutParams.FLAG_SECURE)
>     }
> 
>     override fun onRelease(viewHolder: RecyclerView.ViewHolder, view: View) {
>         activity?.window?.clearFlags(WindowManager.LayoutParams.FLAG_SECURE)
>     }
> })
> ```

Thank you.
