### ISSUE TITLE
希望添加单击返回功能

### ISSUE THREAD

**Issue by androidWht** [iielse/imageviewer#95]
添加单击图片返回。

**Comment by iielse** [comment]
demo 中追加了单击返回的实现.
大致流程：  调用 builder.setVHCustomizer 实现 initialize 方法 拿到imageView对象，设置单击事件。 调用 ImageViewerActionViewModel.dismiss

**Comment by androidWht** [comment]
非常感谢！！请问如何设置全屏浏览，没有发现有相应的配置。

**Comment by iielse** [comment]
'如何设置全屏浏览' 没明白。 现在不是全屏的吗？

**Comment by iielse** [comment]
dev分支 增加了dialog自定义功能 实现 ImageViewerDialogFragment.Factory
https://github.com/iielse/imageviewer/blob/dev/app/src/main/java/com/github/iielse/imageviewer/demo/FullScreenImageViewerDialogFragment.kt

**Comment by iielse** [comment]
@androidWht 你看下是否可以满足全屏预览需求.没太多问题 后面有时间会合进master

**Comment by androidWht** [comment]
@iielse 好的，谢谢！！
