### ISSUE TITLE
要是加入小视频就更好了

### ISSUE THREAD

**Issue by wangfeigit** [iielse/imageviewer#97]

**Comment by iielse** [comment]
其实现有的架构 已经支持小视频了

**Comment by iielse** [comment]
@wangfeigit 我发现事情没那么简单.我要多考虑考虑.你有什么好的想法告诉我呀

**Comment by iielse** [comment]
@wangfeigit 看下，第三个 video 这种可以吗

**Comment by iielse** [comment]
@wangfeigit  新的小视频加好了 . video 分支 写完了.

**Comment by iielse** [comment]
@wangfeigit video 最新代码已经怼上去了，帮忙看下有没有啥问题，或者要补充的需求点，过段时间问题不大就把video发布了。

**Comment by wangfeigit** [comment]
好的我试试
