### ISSUE TITLE
有两个小问题麻烦看一下

### ISSUE THREAD

**Issue by 1wayticket** [iielse/imageviewer#99]
1 图片加载Loader 会加载两次:
       第一次是PhotoViewHolder 的bind方法  第二次是TransitionStartHelper的afterTransition ,在我测试的时候会出现glide加载两次图片闪烁的问题
2 第二就是我按照demo实现的时候发现repository的queryAfter handler发送的应该是
```   
  
        val result = myData.subList(idx + 1, min(idx + pageSize, myData.size ))
```
size-1会导致最后一张滑动不过去
最后希望作者完善下文档,集成了两天....

**Comment by iielse** [comment]
loader确实会加载2次。 第一次建议用那个外面列表加载使用的缓存地址. 第二次可以用高清地址.
.你看我的新demo
 ```
 Glide.with(view).load(it)
                .override(view.width, view.height)
                .placeholder(view.drawable)
                .into(view)
```
闪烁可以 设置placeholder为上个drawable就可以了. 运行下我最新demo 。无闪烁的

2.第二个可能我算错了.小问题  谢谢提示.

文档的话,这段时间没有更多更新的话 会考虑起来. 我感觉你们应该秒懂我的代码.[旺柴]

**Comment by 1wayticket** [comment]
> loader确实会加载2次(是这样设计的.)。执行transition动画的第一个图会load2次。 第一次的时刻在点击的瞬间左右, 建议用那个外面列表加载使用的缓存地址. 第二次的时刻在transition动画执行完毕瞬间左右 可以用高清地址重新load.
> .你看我的新demo
> 
> ```
> Glide.with(view).load(it)
>                .override(view.width, view.height)
>                .placeholder(view.drawable)
>                .into(view)
> ```
> 
> 闪烁可以 设置placeholder为上个drawable就可以了. 运行下我最新demo 。无闪烁的
> 
> 2.第二个.是我模拟网络请求随便写的. 可能应该是我算错了.小问题 谢谢提示. 理论上这里应该是调用网络请求的接口传递id然后向上查询或者向下查询
> 
> 文档的话,这段时间没有更多更新的话 会考虑起来. 我感觉你们应该秒懂我的代码.[旺柴]

多谢了   这下明白了
